### ISSUE TITLE
Интеграция - Assets

### ISSUE THREAD

**Issue by reltec-andrey** [visagio-rus/Ims4#102]
Изменить модель и внести информацию об основных средствах в модель.
Актуальный список средств приложен [Техника.xlsx](https://github.com/visagio-rus/Ims4/files/204044/default.xlsx).
Синхронизацию основных средств не делаем.

**Comment by reltec-andrey** [comment]
Сергей, у тебя немного ui поехал и еще надпись склад вместо подразделения.
Можно тебя попросить прислать файл импорта заполненный.

**Comment by SergeySharonov** [comment]
Андрей, файл импорта приложен.

2016-04-08 14:27 GMT+03:00 Andrey <notifications@github.com>:
