### ISSUE TITLE
Production Consume Management

### ISSUE THREAD

**Issue by reltec-andrey** [visagio-rus/Ims4#46]
Необходимо реализовать пункт 10.7

**Comment by reltec-andrey** [comment]
При подтверждении расхода перемещение происходит не на тот склад.

**Comment by reltec-andrey** [comment]
Списание не работает.

**Comment by evg-fedorov** [comment]
Исрпавлено

**Comment by reltec-andrey** [comment]
Отсутствует этап подтверждения бухгалтером.

**Comment by reltec-andrey** [comment]
Все работает
