### ISSUE TITLE
Single Approach - Filtering, Paging, Sorting

### ISSUE THREAD

**Issue by reltec-andrey** [visagio-rus/Ims4#50]
Необходимо реализовать единообразно во всех view со списками.
Добавить возможность экспорта текущего списка в Excel с учетом фильтров.

**Comment by reltec-andrey** [comment]
Необходимо разобраться с ресурсами, чтобы не было иероглифив и добавить фильтрацию по Enum.
![image](https://cloud.githubusercontent.com/assets/16755736/14076152/d6761688-f4e7-11e5-978d-501760d5727f.png)

**Comment by evg-fedorov** [comment]
We still need date picker for date filter
